name: terraform

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY}} #Make sure that you always have the right keys. Double-check if necessary
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: init
        run: |
          eval `ssh-agent -s`  #this is not a single quote it's a backtick
          ssh-add - <<< '${{secrets.MY_SECRET}}'
          terraform init
      - name: Validate
        run: terraform validate
      - name: Plan
        run: terraform plan
      - name: Apply
        run: terraform apply --auto-approve

        
